dist: bionic

language: C++

services:
  - docker

addons:
  apt:
    update: true
    packages:
      - libinsighttoolkit4-dev
      #- insighttoolkit4-python3
      - cmake
      - g++


stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j2
