dist: focal

language: C++

addons:
  apt:
    update: true
    packages:
      - libinsighttoolkit4-dev
      - libgdcm-dev
      - libvtkgdcm-dev
      - libvtkgdcm-tools
      - libvtkgdcm-java
      #- libvtkgdcm-cil
      # Python 
      - insighttoolkit4-python3
      - python3-gdcm
      - python3-vtkgdcm
      # Build
      - cmake
      - g++


stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j2
